### ISSUE TITLE
Got "FATAL: Startup failure (dev note: apps_startup()) for openssl" when I run 'openssl engine -c'

### ISSUE THREAD

**Issue by penny56** [opencryptoki/openssl-ibmca#115]
Platform: LinuxONE 4 LA1 with DPM mode enabled
OS: rhel 9.3 KVM guest
Versions:
- libica-4.3.0.tar.gz
- openssl-ibmca-2.4.1.tar.gz

Hi,
Usually, when I installed libica and ibmca, I use '$ tee -a /etc/pki/tls/openssl.cnf < sample_file', then comment out 'openssl_conf = default_modules' and move the 'openssl_conf = openssl_def' to the top of cnf file. After that, I can see 'ibmca' engine shows up in the output of 'openssl engine -c'.

This time, I duplicated the same steps running in a rhel 9.3 kvm guest, after that, when I run the 'openssl engine -c', it responsed:
```
[root@a90kvm04-rhel93-079041 ~]# openssl engine -c
FATAL: Startup failure (dev note: apps_startup()) for openssl
000003FF875F3B40:error:40000068:lib(128):ERR_IBMCA_error:dso failure:e_ibmca.c:753:
000003FF875F3B40:error:13000066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:139:section=ibmca_section, name=init, value=1
000003FF875F3B40:error:0700006D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:270:module=engines, value=engine_section retcode=-1
```

Not sure what's happened, the only difference is it is the first time I tried in a kvm guest, not a normal server.

I'll attach the updated '/etc/pki/tls/openssl.cnf' (zipped)configure file, I don't know which log should be added, if anything logs, traces, please let me know.

Thanks~
[41_openssl.cnf.zip](https://github.com/opencryptoki/openssl-ibmca/files/14537781/41_openssl.cnf.zip)

**Comment by penny56** [comment]
I used rpm install rather than 'yum install'.

**Comment by penny56** [comment]
Close this issue since I use yum install and fixed. Thanks.

**Comment by ifranzki** [comment]
OK, just for info:
`ERR_IBMCA_error:dso failure:e_ibmca.c:753` indicates that it can't load the `libica.so` shared library. It probably  was not in library search path or not installed at all.
