### ISSUE TITLE
undefined symbol: rpl_malloc

### ISSUE THREAD

**Issue by p-steuer** [opencryptoki/openssl-ibmca#12]
i get "libibmca.so: undefined symbol: rpl_malloc" on some systems, when using ibmca engine, for example with the "openssl engine -c" command.

this is fixed by removing AC_FUNC_MALLOC from configure.ac.

should this be fixed or am i missing something here ?

**Comment by pvital** [comment]
@p-steuer in which systems have you saw this?

**Comment by p-steuer** [comment]
i saw this once in one of our internal drivers -- no distro affected.

As long as we dont rely on malloc(0) returning a valid pointer, it should not make any difference.

**Comment by p-steuer** [comment]
Also happens on RHEL 7.3:

"LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib openssl engine -c" 
5:06:13 PM
◄
Error configuring OpenSSL
4395919423360:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(/usr/local/lib/libibmca.so): /usr/local/lib/libibmca.so: undefined symbol: rpl_malloc
4395919423360:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
4395919423360:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:eng_dyn.c:450:
4395919423360:error:260BC066:engine routines:INT_ENGINE_CONFIGURE:engine configuration error:eng_cnf.c:204:section=ibmca_section, name=dynamic_path, value=/usr/local/lib/libibmca.so
4395919423360:error:0E07606D:configuration file routines:MODULE_RUN:module initialization error:conf_mod.c:237:module=engines, value=engine_section, retcode=-1
