### ISSUE TITLE
make use of the engine transparent

### ISSUE THREAD

**Issue by p-steuer** [opencryptoki/openssl-ibmca#20]
libcrypto's evp interfaces for ciphers allow to encrypt messages divided in chunks of arbitrary lengths.

ibmca requires the all chunk lenghts except the last one to be multiples of the cipher's block size.

Use of the engine should be made transparent to an application using libcrypto's evp interfaces, in the sense that the behavior is the same \w engine and w\o engine.

**Comment by ifranzki** [comment]
This is obsolete. OpenSSL accelerates ciphers (AES) via CPACF out of the box.
