### ISSUE TITLE
dlclose logic is inverted in ibmca_finish

### ISSUE THREAD

**Issue by ivan-w** [opencryptoki/openssl-ibmca#37]
The test for dlclose() in ibmca_finish() is inverted.

dlclose() returns 0 on success and a non zero value on error. The current code treats success as an error.

**Comment by ivan-w** [comment]
diff --git a/src/e_ibmca.c b/src/e_ibmca.c
index 6b1512a..6feda5d 100644
--- a/src/e_ibmca.c
+++ b/src/e_ibmca.c
@@ -1745,7 +1745,7 @@ static int ibmca_finish(ENGINE * e)
                return 0;
        }
        release_context(ibmca_handle);
-       if (!dlclose(ibmca_dso)) {
+       if (dlclose(ibmca_dso)) {
                IBMCAerr(IBMCA_F_IBMCA_FINISH, IBMCA_R_DSO_FAILURE);
                return 0;
        }

**Comment by ivan-w** [comment]
`diff --git a/src/e_ibmca.c b/src/e_ibmca.c
index 6b1512a..6feda5d 100644
--- a/src/e_ibmca.c
+++ b/src/e_ibmca.c
@@ -1745,7 +1745,7 @@ static int ibmca_finish(ENGINE * e)
                return 0;
        }
        release_context(ibmca_handle);
-       if (!dlclose(ibmca_dso)) {
+       if (dlclose(ibmca_dso)) {
                IBMCAerr(IBMCA_F_IBMCA_FINISH, IBMCA_R_DSO_FAILURE);
                return 0;
        }
`

**Comment by dodys** [comment]
Thanks Ivan for reporting it!
